### ISSUE TITLE
Build sporadically throws errors or doesn't correctly generate images

### ISSUE THREAD

**Issue by vandelpavel** [dreamonkey/responsive-image-loader#44]
I'm currently buildinga in SSR and i 'v noticed that this loader sometime throws error but if you keep re run it will work and even if it doesn't throws errors check if all the images are correctly generated.
**Images can be corrupted when:**

- Using the `path` feature and use different images on different sizes.
- Probably using symbols or spaces in image's names.
- On small wiewport rather then larger or viceversa
- On different browsers may broke

1. Create a project (in my case SSR)
2. Use the loader in many images
3. Try using all the feature
4. Control other browsers

5. Since i'm in SSR i find this issue only when refreshing the page

**Expected behavior**
Error occur and not all images are correctly generated.

**Workaround**
Run many builds until it works (it may took some time). Then try to control if you see some images that are missing.
The best way is to re build the project and copy all the old images in the new img folder. You can ignore images that already exist.
It could be possible that some images still be missing. In that case:
- Save the complete build with the missing image.
- Change all `responsive` reference to disable the loader everywhere except on the image that doesn't show. (i simply add a z after to have `responsivez`)
- Now build the project and since you only need to process one image it will be fast and you have almost 0 chance to fail.
- At the end copy all the processed images(only the ones you have processed not all) in the complete build and now the image should work.

**Desktop (please complete the following information):**
 - OS: Windows (10)
 - Browser Tested on firefox, safari and chrome

**Comment by IlCallo** [comment]
This is due to local docker pod blocking the requests, probably due to nginx throttle.
We are currently DOSsing the docker instance right now when too many images are requested at the same time.
When this happens, we get an error and won't emit the file (as it won't be generated).

We must either limit the request ratio or manage the request block and force a retry until it gets accepted.

**Comment by IlCallo** [comment]
Solved with version 0.6, the problem was a race condition with the thumbor docker process teardown
