### ISSUE TITLE
Error raplace  and _callee2$

### ISSUE THREAD

**Issue by vandelpavel** [dreamonkey/responsive-image-loader#45]
If you get an error something like:
```
TypeError: Cannot read property 'replace' of undefined

  - index.min.js:1 _callee2$
```
 you probably forgotten to run doker on you system.

It could be a good idea to write a message and throw the error almost immediately instead of after all the building time

**Comment by IlCallo** [comment]
Duplicate of dreamonkey/responsive-image-plugin#4
